version: "3"

services:
    front:
        build:
            context: .
            dockerfile: ./front/Dockerfile
        ports:
            - 80:80
        command: npm start

    back:
        build:
            context: .
            dockerfile: ./back/Dockerfile
        ports:
            - 3000:3000
        command: npm start
        hostname: back